spring:
  application:
    name: currency-exchange-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/currency-exchange-db

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka



